version: "3"

services: 
   haproxy:
    networks:
        client1:
          ipv4_address: 192.168.14.2

    container_name: haproxy
    image: haproxytech/haproxy-debian:2.7

    volumes: 
      - "./config:/usr/local/etc/haproxy:ro"

    ports:
      - "8000:8000"
      - "8404:8404"

networks:
  client1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.14.0/24
          gateway: 192.168.14.1